import { PageConfig, PageTheme } from './types';

export const THEME_PRESETS: { name: string; theme: Partial<PageTheme> }[] = [
  {
    name: 'Bold Typography (Dark)',
    theme: {
      primaryColor: '#ffffff',
      secondaryColor: '#171717',
      accentColor: '#38bdf8',
      gradientAngle: 180,
      fontFamily: "'Space Grotesk', sans-serif",
      borderRadius: 6,
      cardBgColor: '#141414',
      cardTextColor: '#f5f5f5',
      bodyBgColor: '#0a0a0a',
      bodyTextColor: '#f5f5f5',
      heroTextColor: '#ffffff',
      footerBgColor: '#050505',
      footerTextColor: '#a3a3a3',
      footerLinkColor: '#ffffff',
    },
  },
  {
    name: 'Bold Typography (High Contrast)',
    theme: {
      primaryColor: '#ffffff',
      secondaryColor: '#262626',
      accentColor: '#facc15',
      gradientAngle: 135,
      fontFamily: "'Syne', sans-serif",
      borderRadius: 4,
      cardBgColor: '#18181b',
      cardTextColor: '#fafafa',
      bodyBgColor: '#09090b',
      bodyTextColor: '#f4f4f5',
      heroTextColor: '#ffffff',
      footerBgColor: '#000000',
      footerTextColor: '#a1a1aa',
      footerLinkColor: '#facc15',
    },
  },
  {
    name: 'Original Purple Gradient',
    theme: {
      primaryColor: '#667eea',
      secondaryColor: '#764ba2',
      accentColor: '#48bb78',
      gradientAngle: 135,
      fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
      borderRadius: 8,
      cardBgColor: '#f4f4f4',
      cardTextColor: '#333333',
      bodyBgColor: '#ffffff',
      bodyTextColor: '#333333',
      heroTextColor: '#ffffff',
      footerBgColor: '#333333',
      footerTextColor: '#ffffff',
      footerLinkColor: '#667eea',
    },
  },
  {
    name: 'Ocean Cyan & Blue',
    theme: {
      primaryColor: '#0ea5e9',
      secondaryColor: '#2563eb',
      accentColor: '#06b6d4',
      gradientAngle: 120,
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      borderRadius: 12,
      cardBgColor: '#f8fafc',
      cardTextColor: '#0f172a',
      bodyBgColor: '#ffffff',
      bodyTextColor: '#334155',
      heroTextColor: '#ffffff',
      footerBgColor: '#0f172a',
      footerTextColor: '#94a3b8',
      footerLinkColor: '#38bdf8',
    },
  },
  {
    name: 'Sunset Coral & Crimson',
    theme: {
      primaryColor: '#f43f5e',
      secondaryColor: '#fb923c',
      accentColor: '#f59e0b',
      gradientAngle: 135,
      fontFamily: "'Outfit', sans-serif",
      borderRadius: 10,
      cardBgColor: '#fff7ed',
      cardTextColor: '#431407',
      bodyBgColor: '#ffffff',
      bodyTextColor: '#292524',
      heroTextColor: '#ffffff',
      footerBgColor: '#1c1917',
      footerTextColor: '#e7e5e4',
      footerLinkColor: '#fb923c',
    },
  },
  {
    name: 'Emerald Forest & Teal',
    theme: {
      primaryColor: '#059669',
      secondaryColor: '#0d9488',
      accentColor: '#10b981',
      gradientAngle: 140,
      fontFamily: "'DM Sans', sans-serif",
      borderRadius: 8,
      cardBgColor: '#f0fdf4',
      cardTextColor: '#064e3b',
      bodyBgColor: '#ffffff',
      bodyTextColor: '#1f2937',
      heroTextColor: '#ffffff',
      footerBgColor: '#064e3b',
      footerTextColor: '#a7f3d0',
      footerLinkColor: '#34d399',
    },
  },
  {
    name: 'Midnight Modern Slate',
    theme: {
      primaryColor: '#3b82f6',
      secondaryColor: '#1e293b',
      accentColor: '#60a5fa',
      gradientAngle: 150,
      fontFamily: "'Inter', sans-serif",
      borderRadius: 12,
      cardBgColor: '#1e293b',
      cardTextColor: '#f8fafc',
      bodyBgColor: '#0f172a',
      bodyTextColor: '#cbd5e1',
      heroTextColor: '#ffffff',
      footerBgColor: '#020617',
      footerTextColor: '#94a3b8',
      footerLinkColor: '#60a5fa',
    },
  },
  {
    name: 'Editorial Serif & Rose',
    theme: {
      primaryColor: '#881337',
      secondaryColor: '#be123c',
      accentColor: '#f43f5e',
      gradientAngle: 125,
      fontFamily: "'Playfair Display', serif",
      borderRadius: 4,
      cardBgColor: '#fff1f2',
      cardTextColor: '#4c0519',
      bodyBgColor: '#fffafb',
      bodyTextColor: '#4c0519',
      heroTextColor: '#ffffff',
      footerBgColor: '#4c0519',
      footerTextColor: '#fecdd3',
      footerLinkColor: '#fb7185',
    },
  },
];

export const FONT_OPTIONS = [
  { label: 'Space Grotesk (Bold Display)', value: "'Space Grotesk', sans-serif" },
  { label: 'Syne (Ultra Bold)', value: "'Syne', sans-serif" },
  { label: 'Inter (Clean Sans)', value: "'Inter', sans-serif" },
  { label: 'Plus Jakarta Sans', value: "'Plus Jakarta Sans', sans-serif" },
  { label: 'Outfit (Modern)', value: "'Outfit', sans-serif" },
  { label: 'Poppins', value: "'Poppins', sans-serif" },
  { label: 'DM Sans', value: "'DM Sans', sans-serif" },
  { label: 'Playfair Display (Serif)', value: "'Playfair Display', serif" },
  { label: 'Segoe UI / System', value: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif" },
];

export const DEFAULT_PAGE_CONFIG: PageConfig = {
  theme: {
    primaryColor: '#ffffff',
    secondaryColor: '#171717',
    accentColor: '#38bdf8',
    gradientAngle: 180,
    fontFamily: "'Space Grotesk', sans-serif",
    borderRadius: 6,
    cardBgColor: '#141414',
    cardTextColor: '#f5f5f5',
    bodyBgColor: '#0a0a0a',
    bodyTextColor: '#f5f5f5',
    heroTextColor: '#ffffff',
    footerBgColor: '#050505',
    footerTextColor: '#a3a3a3',
    footerLinkColor: '#ffffff',
  },
  header: {
    brandName: 'MyBrand',
    brandIcon: '',
    navLinks: [
      { id: '1', label: 'Home', url: '#home' },
      { id: '2', label: 'Features', url: '#features' },
      { id: '3', label: 'About', url: '#about' },
      { id: '4', label: 'Contact', url: '#contact' },
    ],
    isSticky: true,
    headerBgStyle: 'gradient',
    headerBgColor: '#667eea',
  },
  hero: {
    title: 'Welcome to Our Website',
    subtitle: 'Build something amazing with us',
    ctaText: 'Get Started',
    ctaUrl: '#features',
    secondaryCtaText: '',
    secondaryCtaUrl: '',
    alignment: 'center',
    paddingY: 6,
    showBadge: false,
    badgeText: '✨ Discover What is Possible',
  },
  features: {
    sectionTitle: 'Our Features',
    sectionSubtitle: '',
    columns: 3,
    cardHoverEffect: true,
    items: [
      {
        id: '1',
        icon: '⚡',
        title: 'Fast',
        description: 'Lightning-fast performance optimized for speed',
        tag: 'Speed',
      },
      {
        id: '2',
        icon: '🔒',
        title: 'Secure',
        description: 'Enterprise-grade security for your peace of mind',
        tag: 'Security',
      },
      {
        id: '3',
        icon: '📱',
        title: 'Responsive',
        description: 'Works perfectly on all devices and screen sizes',
        tag: 'Design',
      },
    ],
  },
  about: {
    sectionTitle: 'About Us',
    content:
      'We are committed to delivering high-quality solutions that exceed expectations. Our team of experts is dedicated to helping you succeed.',
    showStats: false,
    stats: [
      { id: '1', label: 'Happy Customers', value: '10,000+' },
      { id: '2', label: 'Uptime Guarantee', value: '99.9%' },
      { id: '3', label: 'Global Servers', value: '24/7' },
    ],
  },
  testimonials: {
    enabled: false,
    sectionTitle: 'What Our Clients Say',
    items: [
      {
        id: '1',
        name: 'Sarah Jenkins',
        role: 'Founder & CEO',
        avatar: '👩‍💼',
        quote: 'This template helped us launch our product in hours instead of days. Exceptional quality!',
        rating: 5,
      },
      {
        id: '2',
        name: 'Alex Rivera',
        role: 'Lead Architect',
        avatar: '👨‍💻',
        quote: 'The performance and clean responsive layout made an immediate positive impact on our conversions.',
        rating: 5,
      },
    ],
  },
  ctaBanner: {
    enabled: false,
    title: 'Ready to Transform Your Workflow?',
    subtitle: 'Join thousands of creators and businesses already using our solution today.',
    buttonText: 'Get Started Free',
    buttonUrl: '#contact',
  },
  faq: {
    enabled: false,
    sectionTitle: 'Frequently Asked Questions',
    items: [
      {
        id: '1',
        question: 'How easy is it to customize this page?',
        answer: 'You can edit every single piece of text directly in your browser, switch color palettes, rearrange cards, and export clean standalone HTML.',
      },
      {
        id: '2',
        question: 'Can I download the code for my own hosting?',
        answer: 'Yes! Click the Export button at the top to download a self-contained, lightweight index.html file ready to deploy anywhere.',
      },
    ],
  },
  footer: {
    copyright: '© 2024 MyBrand. All rights reserved.',
    links: [
      { id: '1', label: 'Contact Us', url: 'mailto:info@example.com' },
      { id: '2', label: 'Privacy Policy', url: '#' },
      { id: '3', label: 'Terms of Service', url: '#' },
    ],
    showSocials: false,
    socials: [
      { platform: 'Twitter', url: '#' },
      { platform: 'GitHub', url: '#' },
      { platform: 'LinkedIn', url: '#' },
    ],
  },
};
